name: base_repository_bya2
description: High Level Implementation for API calls. Based on Dio. Further Documentation coming soon.


repository: https://github.com/AradhyaNepal/base_repository_bya2
issue_tracker: https://github.com/AradhyaNepal/base_repository_bya2/issues
version: 0.0.7

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http_parser: ^4.0.2
  dio: ^5.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0